In [1]:
# -*- coding: utf-8 -*-
"""
Created on Tue Aug 27 22:26:45 2024

@author: rcyajour
"""

import pandas as pd
import csv

link = "wineQT.csv"
w = pd.read_csv(link)
w

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,0
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,1
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,2
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,3
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1138,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6,1592
1139,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6,1593
1140,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5,1594
1141,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6,1595
1142,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5,1597

In [3]:
#storing all the column values as float.
# Stored as a list of dictionaries with each row as list containing dictionary of columns as key and data as values
wine=[]
w1=open('wineQT.csv', mode='r')
reader = csv.DictReader(w1)
for r in reader:   #r = row , k = key
    for k in r:
        r[k] = float(r[k])
       
    wine.append(r)
len(wine)

1143

In [4]:
#QUALITY ATTRIBUTE VALUES :
# 0(bad) if x<=6 and 1(good) if x>6.
q='quality'
for r in wine:
    if r[q] > 6:
        r[q] = 1
    else:
        r[q] = 0
wine[0].keys()

dict_keys(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol', 'quality', 'Id'])

In [5]:
#MIN MAX SCALING TECHNIQUE :

col =[]
for i in wine[0].keys():
   # print(i)
    if i!= q:       #Excluding 'quality' column from min max scaling
        col+=[i]
        
col

#creating two rows to store min and max values of each column
mins = {c: float('inf') for c in col}
maxs = {c: float('-inf') for c in col}

for r in wine:
    for c in col:
        if r[c] < mins[c]:
            mins[c] = r[c]
        if r[c] > maxs[c]:
            maxs[c] = r[c]
mins,maxs

({'fixed acidity': 4.6,
  'volatile acidity': 0.12,
  'citric acid': 0.0,
  'residual sugar': 0.9,
  'chlorides': 0.012,
  'free sulfur dioxide': 1.0,
  'total sulfur dioxide': 6.0,
  'density': 0.9900700000000001,
  'pH': 2.74,
  'sulphates': 0.33,
  'alcohol': 8.4,
  'Id': 0.0},
 {'fixed acidity': 15.9,
  'volatile acidity': 1.58,
  'citric acid': 1.0,
  'residual sugar': 15.5,
  'chlorides': 0.611,
  'free sulfur dioxide': 68.0,
  'total sulfur dioxide': 289.0,
  'density': 1.00369,
  'pH': 4.01,
  'sulphates': 2.0,
  'alcohol': 14.9,
  'Id': 1597.0})

In [12]:
# MIN-MAX SCALING
for r in wine:
    for c in col:
        r[c] = (r[c] - mins[c]) / (maxs[c] - mins[c])  #Normalization formula

In [16]:
w2= open('wineQT_after_min_max.csv', mode='w', newline='')   #write normalized data to new file
writer = csv.DictWriter(w2, fieldnames=wine[0].keys())
writer.writeheader()
writer.writerows(wine)

In [17]:
w3=pd.read_csv('wineQT_after_min_max.csv')
w3

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,-0.446559,-0.116026,0.00,-0.066174,0.627414,-0.015152,-0.021277,-1.267566e+07,-6.014122,-0.411506,-1.526331,0,0.000000e+00
1,-0.446557,-0.088892,0.00,-0.066172,0.912705,-0.015151,-0.021277,-1.480926e+07,-6.107952,-0.402267,-1.526296,0,9.626655e-17
2,-0.446557,-0.106981,0.04,-0.066173,0.834898,-0.015152,-0.021277,-1.438254e+07,-6.089792,-0.404577,-1.526296,0,1.925331e-16
3,-0.446539,-0.179338,0.56,-0.066174,0.614446,-0.015152,-0.021277,-1.224893e+07,-6.120059,-0.409966,-1.526296,0,2.887997e-16
4,-0.446559,-0.116026,0.00,-0.066174,0.627414,-0.015152,-0.021277,-1.267566e+07,-6.014122,-0.411506,-1.526331,0,3.850662e-16
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1138,-0.446565,-0.144667,0.13,-0.066173,0.627414,-0.015151,-0.021277,-1.707089e+07,-6.041363,-0.396878,-1.526193,0,1.532564e-13
1139,-0.446563,-0.128085,0.08,-0.066174,0.523671,-0.015151,-0.021277,-1.542801e+07,-6.041363,-0.391489,-1.526322,0,1.533526e-13
1140,-0.446566,-0.131100,0.08,-0.066173,0.808963,-0.015151,-0.021277,-1.886312e+07,-6.032283,-0.409966,-1.526236,0,1.534489e-13
1141,-0.446567,-0.138637,0.10,-0.066173,0.445865,-0.015151,-0.021277,-1.839372e+07,-6.011095,-0.396108,-1.526176,0,1.535452e-13
1142,-0.446567,-0.124317,0.12,-0.066173,0.614446,-0.015151,-0.021277,-1.764696e+07,-5.995961,-0.399958,-1.526262,0,1.537377e-13

## Why we use MIN- MAX SCALING?

Different features in the dataset wineQT have different units and scales (Ex: Density, pH, Acid Levels and Quality). 

Min-max scaling standardizes these features to a uniform scale of range 0 to 1 ensuring that no single feature dominates others due to its larger magnitude.

This makes interpretation easier and relatively simpler making algorithms that rely on distance calculations, like k-means clustering and k-nearest neighbors, perform better.

Large feature values can lead to numeric instability in some algorithms, especially in
matrix operations. Min-max scaling helps in preventing overflow and underflow errors.

**SPECIFIC APPLICATIONS:**

In **neural networks**, inputs are often scaled to [0, 1] or [-1, 1] to ensure that the
activation functions (like sigmoid or tanh) work effectively.

**Principal Component Analysis (PCA)** benefits from scaling, as itâ€™s sensitive to the
variances of the input features. Without scaling, features with higher variance could
dominate the PCA.